version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: sc_user_db
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
    ports:
      - 5432:5432